name: Build Windows Executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Generate spec file
        run: pyi-makespec --name "PsychRef" "src/psychref.py"

      - name: Modify spec file
        run: |
          $content = Get-Content -Path PsychRef.spec
          $content = $content -replace "datas=\[\]", "datas=[('src/*.py', '.')]"
          $content = $content -replace "hiddenimports=\[\]", "hiddenimports=['gui', 'utils', 'constants', 'customtkinter']"
          $content | Set-Content -Path PsychRef.spec

      - name: Build windows .exe
        run: |
          .venv\Scripts\Activate.ps1
          pyinstaller --clean --debug PsychRef.spec

      - name: Zip PsychRef directory
        run: Compress-Archive -Path dist\PsychRef -DestinationPath PsychRef.zip

      - uses: actions/upload-artifact@v4
        with:
          name: PsychRef.zip
          path: PsychRef.zip
          if-no-files-found: error
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: PsychRef.zip
          path: ./
      - name: Generate release timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v2
        with:
          files: "./PsychRef.zip"
          tag_name: "v${{ steps.timestamp.outputs.timestamp }}"
